-- phpMyAdmin SQL Dump
-- version 4.4.12
-- http://www.phpmyadmin.net
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 23 Ara 2016, 21:58:41
-- Sunucu sürümü: 5.6.25
-- PHP Sürümü: 5.6.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `nirvana`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `albumler`
--

CREATE TABLE IF NOT EXISTS `albumler` (
  `album_id` int(12) NOT NULL,
  `album_adi` varchar(50) NOT NULL,
  `album_yili` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `albumler`
--

INSERT INTO `albumler` (`album_id`, `album_adi`, `album_yili`) VALUES
(1, 'Bleach', 1989),
(2, 'Nevermind', 1991),
(3, ' In Utero', 1993);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `sarkilar`
--

CREATE TABLE IF NOT EXISTS `sarkilar` (
  `sarki_id` int(12) NOT NULL,
  `sarki_adi` varchar(50) NOT NULL,
  `sozler` text NOT NULL,
  `album_id` int(11) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=latin1;

--
-- Tablo döküm verisi `sarkilar`
--

INSERT INTO `sarkilar` (`sarki_id`, `sarki_adi`, `sozler`, `album_id`) VALUES
(1, 'Blew', 'If you wouldn''t mind I would like it blew\nIf you wouldn''t mind I would like it loose\nIf you wouldn''t care I would like to leave\nIf you wouldn''t mind I would like to breathe\n\nIs there another reason for your stay\nCould you believe him when you discussed his stain?\nHere is another word that rhymes with shame\n\nIf you wouldn''t mind I would like it blew\nIf you wouldn''t mind I would like it loose\nIf you wouldn''t care I would like to bleed\nIf you wouldn''t mind I would like to breathe.\n\nIs there another reason for your stay\nCould you believe him when you discussed his stain?\nHere is another word that rhymes with shame\n\nYou could do anything (x8)', 1),
(2, 'Floyd the Barber', 'Hello Cobain come on in\r\nFloyd now says my hairy chin\r\nSit down in the chair don''t be afraid\r\nSteaming hot towel on my face\r\n\r\nI''m ashamed\r\n(x3)\r\n\r\nBarber ties me to the chair\r\nI can''t see I''m really scared\r\nFloyd burns alright he''ll sell -?\r\nThey depress against my nails\r\n\r\nI was ashamed\r\n(x3)\r\n\r\nLies and suffers in the room\r\nOh reality / Looking at me I presume\r\nThey take turns and cut me up\r\nI die smothered and he''s not\r\n\r\nI was ashamed\r\n(x3)', 1),
(3, 'About a Girl', 'I need an easy friend\r\nI do whip her into land - ?\r\nI don''t think you fit this shoe\r\nI do, won''t you have a clue\r\n\r\nI''ll take advantage while\r\nYou hang me out to dry\r\nBut I can''t see you every night\r\nFree\r\n\r\nI''m standing in your line\r\nI do hope you have the time\r\nI do pick a number too\r\nI do keep a date with you\r\n\r\nI''ll take advantage while\r\nYou hang me out to dry\r\nBut I can''t see you every night\r\nFree\r\n\r\nI need an easy friend\r\nI do whip her in to land\r\nI do think you fit this shoe\r\nI do won''t you have a clue\r\n\r\nI''ll take advantage while\r\nYou hang me out to dry\r\nBut I can''t see you every night\r\nNo I can''t see you every night\r\nFree\r\nI do (x4)', 1),
(4, 'School', 'Won''t you believe it\r\nIt''s just my luck\r\n(x4)\r\n\r\nNo recess\r\n(x3)\r\n\r\nWon''t you believe it\r\nIt''s just my luck\r\n(x4)\r\n\r\nNo recess\r\n(x3)\r\n\r\nYou''re in high school again\r\n(x8)\r\n\r\nNo recess\r\n(x7)', 1),
(5, 'Love Buzz', 'Would you believe me when I tell you\r\nYou are the queen of my heart\r\nPlease don''t deceive me when I hurt you\r\nJust ain''t the way it seems\r\n\r\nCan you feel my love buzz (x4)\r\n\r\n(repeated)', 1),
(6, 'Paper Cuts', 'When I''m feeling tired\r\nShe puts you through the door\r\nI crawl towards the cursed alley\r\nSometimes I can''t find my way\r\nThis curtain''s (Kurt is?) spellbound (still round)\r\nSo get all that you can\r\nA cool man is toughening/too plain\r\nA good hosing down\r\n\r\nWhen the hate in my field (ma)eternal all four\r\nCannot look me in the eyes\r\nBut I asked the years ham radio blew\r\nAnd the car, twist, mouth, fear! Yaaah!\r\nI think so\r\nI think so\r\nI think so\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana...\r\n\r\nBack when ''twas a party\r\nI scratched with my nails\r\nI see now that she''s just like me\r\nWhy do they not try to escape?\r\nThey bring out the holy ones\r\nThey pointed my way\r\nThey come with the flashing lights\r\nAnd take my family away\r\n\r\nAn-gr-y later I am known to\r\nSlap some friends of ridicule\r\nMy whole existence is for your fears\r\nAnd that is why I''m here with you!\r\nDon''t taaaake\r\nMe awaaaaay\r\nYou''re round\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana\r\nNirvana...', 1),
(7, 'Negative Creep', 'This is out of our range (x3)\r\nno\r\nThis is getting to be (x3)\r\ngross\r\nI''m a negative creep (x3)\r\nand I''m stoned\r\nI''m a negative creep (x3)\r\nand I''m\r\nI''m\r\nDaddy''s little girl ain''t a girl no more (x6)\r\n\r\nThis is out of our range (x3)\r\nno\r\nThis is getting to be (x3)\r\ngross\r\nI''m a negative creep (x3)\r\nand I''m stoned\r\nI''m a negative creep (x3)\r\nand I''m\r\nI''m\r\nDaddy''s little girl ain''t a girl no more (x4)\r\n\r\nDaddy''s little girl ain''t a girl no more (x8)', 1),
(8, 'Scoff', 'In my eyes\r\nI''m not lazy\r\nIn my face\r\nIt''s not over\r\nIn your room\r\nI''m not older\r\nIn your eyes\r\nI''m not worth it\r\nGimme back my alcohol (x8)\r\n\r\n(First:)\r\nGive me all your... (x 6)\r\n\r\n(First and second repetitions:)\r\nGive me all your... (x 5)\r\nGive me your\r\nLove! (?)\r\n\r\nFuck!', 1),
(9, 'Swap Meet', 'They need a lifestyle that is comfortable\r\nThey travel far to keep their stomachs full\r\nThey make a living off of arts and crafts\r\nThe conversations just would (n)ever laugh (?)\r\nThey make a deal when they come to town\r\nThe Sunday swap meet is a battle ground\r\nShe loves it more than he will ever know\r\nHe loves it more than he will ever show\r\nKeeps his cigarettes close to his heart\r\nKeeps her photographs close to her heart\r\nKeeps the bus-i-ness close to the heart\r\n\r\n(x3)', 1),
(10, 'Mr. Moustache', 'Fill me in on your new vision\r\nWake me up with indecision\r\nHelp me trust your mind and wisdom\r\nYes I eat cow I am not proud.\r\n\r\nShow me how you question, question\r\nLead the way to my temptations\r\nTake my hand and keep it clean\r\nAs I eat cow I am not proud.\r\n\r\nIs it an easychair?\r\nOversized rock\r\nI don''t like you anyway\r\nSilver metal box\r\n\r\nI''m new\r\nI''m new\r\n(all again, then:)\r\n\r\nI''m who?\r\nI''m you--aaaahh! Aaaah!', 1),
(11, 'Sifting', 'Afraid to grade\r\nWouldn''t it be fun?\r\nCross, self-loss\r\nWouldn''t it be fun?\r\nWet your bed\r\nWouldn''t it be fun?\r\nSome fear none\r\nWouldn''t it be fun?\r\n\r\nYour eyes\r\nTreat yourself\r\n(x3)\r\nTreat yourself\r\n\r\nDon''t have nothing for you (x6)\r\nDon''t have nothing but (for?) you\r\n\r\nSmell the smell\r\nWouldn''t it be fun?\r\nSearch for a church\r\nWouldn''t it be fun?\r\nWet your bed\r\nWouldn''t it be fun?\r\nCold is gold\r\nWouldn''t it be fun?\r\n\r\nYour eyes\r\nTreat yourself\r\n(x3)\r\nTreat yourself (x2)\r\n\r\nDon''t have nothing for you(x7)\r\n\r\nDon''t have nothing for you (x9)', 1),
(12, 'Big Cheese', 'Big cheese make me\r\nMine says, "Go to the office"\r\n\r\nBig cheese Make me\r\nMine says, "One that stays"\r\n\r\nBlack is black, straight back\r\nNeed more enemies\r\nShow you all what a man is\r\n\r\nBig lies make my\r\nMine says "Go to the office"\r\n\r\nBig cheese Make me\r\nMessage? What is it?\r\n\r\nBlack is black straight back\r\nNeed more enemies\r\nShe is glue how are you?', 1),
(13, 'Downer', 'Put your sincerity\r\nI''ve got a royalty\r\nDefending your country\r\nWish away\r\n\r\nI''ve had a lobotomy\r\nSave your family\r\nSurrealistic fantasy\r\nBad boy\r\n\r\nFight!\r\n\r\nAll we know is\r\nRestitution\r\nLiving out your\r\nDate of future\r\nThere''s a hope\r\nPlease show me faster\r\nDon''t forget\r\nTo pass a riot\r\n\r\nSomebody served a dinner\r\nMuch like I am\r\nI know I can''t\r\nMake enough although\r\nIf you go along\r\nI sing your song\r\n\r\nSickening pessimists\r\nPicketing masses\r\nSeparated communists\r\nApocalyptic bastards\r\nRinkydink God\r\nFor putting me on this Earth\r\nBeing very frivolous\r\nDeath in mind\r\n\r\nNurse!\r\n\r\nAll we know is\r\nRestitution\r\nLiving out your\r\nDate of future\r\nThere''s a hope\r\nPlease send it faster\r\nDon''t forget\r\nTo pass a riot\r\n\r\nSomebody served a dinner\r\nMuch like I am\r\nI know I can''t\r\nMake enough although\r\nIf you go along\r\nI sing your song.', 1),
(14, 'Smells Like Teen Spirit', 'Load up on guns and\r\nBring your friends\r\nIt''s fun to lose\r\nAnd to pretend\r\nShe''s over bored\r\nAnd self assured\r\nOh no, I know\r\nA dirty word\r\n\r\nhello, how low?\r\n\r\nWith the lights out it''s less dangerous\r\nHere we are now\r\nEntertain us\r\nI feel stupid and contagious\r\nHere we are now\r\nEntertain us\r\nA mulatto\r\nAn albino\r\nA mosquito\r\nMy Libido\r\nYeah\r\n\r\nI''m worse at what I do best\r\nAnd for this gift I feel blessed\r\nOur little group has always been\r\nAnd always will until the end\r\n\r\nhello, how low?\r\n\r\nWith the lights out it''s less dangerous\r\nHere we are now\r\nEntertain us\r\nI feel stupid and contagious\r\nHere we are now\r\nEntertain us\r\nA mulatto\r\nAn albino\r\nA mosquito\r\nMy Libido\r\nYeah\r\n\r\nAnd I forget\r\nJust why I taste\r\nOh yeah, I guess it makes me smile\r\nI found it hard\r\nIt was hard to find\r\nOh well, whatever, nevermind\r\n\r\nhello, how low?\r\n\r\nWith the lights out it''s less dangerous\r\nHere we are now\r\nEntertain us\r\nI feel stupid and contagious\r\nHere we are now\r\nEntertain us\r\nA mulatto\r\nAn albino\r\nA mosquito\r\nMy Libido\r\nYeah, a denial\r\nA denial\r\nA denial...', 2),
(15, 'In Bloom', 'Sell the kids for food\r\nWeather changes moods\r\nSpring is here again\r\nReproductive glands\r\n\r\nHe''s the one\r\nWho likes all the pretty songs\r\nAnd he likes to sing along\r\nAnd he likes to shoot his gun\r\nBut he knows not what it mean\r\nKnows not what it mean\r\nAnd I say\r\nHe''s the one\r\nWho likes all the pretty songs\r\nAnd he likes to sing along\r\nAnd he likes to shoot his gun\r\nBut he knows not what it mean\r\nKnows not what it mean\r\nAnd I say yeah\r\n\r\nWe can have some more\r\nNature is a whore\r\nBruises on the fruit\r\nTender age in bloom\r\n\r\nHe''s the one\r\nWho likes all the pretty songs\r\nAnd he likes to sing along\r\nAnd he likes to shoot his gun\r\nBut he knows not what it mean\r\nKnows not what it mean\r\nAnd I say\r\nHe''s the one\r\nWho likes all the pretty songs\r\nAnd he likes to sing along\r\nAnd he likes to shoot his gun\r\nBut he knows not what it mean\r\nKnows not what it mean\r\nAnd I say yeah\r\n\r\nHe''s the one\r\nWho likes all the pretty songs\r\nAnd he likes to sing along\r\nAnd he likes to shoot his gun\r\nBut he knows not what it mean\r\nKnows not what it mean\r\nAnd I say\r\nHe''s the one\r\nWho likes all the pretty songs\r\nAnd he likes to sing along\r\nAnd he likes to shoot his gun\r\nBut he knows not what it mean\r\nKnows not what it mean\r\nAnd I say yeah', 2),
(16, 'Breed', 'I don''t care\r\nI don''t care\r\nI don''t care\r\nI don''t care\r\nI don''t care\r\nCare if I''m old\r\n\r\nI don''t mind\r\nI don''t mind\r\nI don''t mind\r\nI don''t mind\r\nmind\r\nDon''t have a mind\r\n\r\nGet way\r\nGet way\r\nGet way\r\nGet way\r\nGet way\r\nWay from your home\r\n\r\nI''m afraid\r\nI''m afraid\r\nI''m afraid\r\nI''m afraid\r\nFraid, of a ghost\r\n\r\nEven if you have\r\nEven if you need\r\nI don''t mean to stare\r\nWe don''t have to breed\r\nWe can plant a house\r\nWe can build a tree\r\nI don''t even care\r\nWe could have all three\r\n\r\nShe said', 2),
(17, 'Lithium', 'I''m so happy\r\nCause today I found my friends\r\nThey''re in my head\r\nI''m so ugly\r\nBut that''s ok, ''cause so are you\r\nWe''ve broke our mirrors\r\nSunday morning\r\nIs everyday for all I care\r\nAnd I''m not scared\r\nLight my candles\r\nIn a daze ''cause I''ve found god\r\n\r\nYeah\r\n\r\nI''m so lonely and\r\nThat''s ok, I shaved my head\r\nAnd I''m not sad\r\nAnd just maybe\r\nI''m to blame for all I''ve heard\r\nAnd I''m not sure\r\nI''m so excited\r\nI can''t wait to meet you there\r\nAnd I dont'' care\r\nI''m so horny but\r\nThat''s ok, my will is good\r\n\r\nYeah\r\n\r\nI like it\r\nI''m not gonna crack\r\nI miss you\r\nI''m not gonna crack\r\nI love you\r\nI''m not gonna crack\r\nI killed you\r\nI''m not gonna crack\r\nI like it\r\nI''m not gonna crack\r\nI miss you\r\nI''m not gonna crack\r\nI love you\r\nI''m not gonna crack\r\nI killed you\r\nI''m not gonna crack\r\n\r\nI''m so happy\r\nCause today I found my friends\r\nThey''re in my head\r\nI''m so ugly\r\nBut that''s ok, ''cause so are you\r\nWe''ve broke our mirrors\r\nSunday morning\r\nIs everyday for all I care\r\nAnd I''m not scared\r\nLight my candles\r\nIn a daze ''cause I''ve found god\r\n\r\nYeah\r\n\r\nI like it\r\nI''m not gonna crack\r\nI miss you\r\nI''m not gonna crack\r\nI love you\r\nI''m not gonna crack\r\nI killed you\r\nI''m not gonna crack\r\nI like it\r\nI''m not gonna crack\r\nI miss you\r\nI''m not gonna crack\r\nI love you\r\nI''m not gonna crack\r\nI killed you\r\nI''m not gonna crack', 2),
(18, 'Polly', 'Polly wants a cracker\r\nThink I should get off of her first\r\nI think she wants some water\r\nTo put out the blow torch\r\n\r\nIt isn''t me\r\nWe have some seed\r\nLet me clip\r\nYour dirty wings\r\nLet me take a ride\r\nDon''t hurt yourself\r\nI want some help\r\nTo help myself\r\nI''ve got some rope\r\nYou have been told\r\nI promise you\r\nI have been true\r\nLet me take a ride\r\nDon''t hurt yourself\r\nI want some help\r\nTo help myself\r\n\r\nPolly wants a cracker\r\nMaybe she would like more food\r\nShe asks me to untie her\r\nA chase would be nice for a few\r\n\r\nIt isn''t me\r\nWe have some seed\r\nLet me clip\r\nYour dirty wings\r\nLet me take a ride\r\nDon''t hurt yourself\r\nI want some help\r\nTo help myself\r\nI''ve got some rope\r\nYou have been told\r\nI promise you\r\nI have been true\r\nLet me take a ride\r\nDon''t hurt yourself\r\nI want some help\r\nTo help myself\r\n\r\n{Polly said}\r\nPolly says her back hurts\r\nAnd she''s just as bored as me\r\nShe caught me off my guard\r\nIt amazes me, the will of instinct\r\n\r\nIt isn''t me\r\nWe have some seed\r\nLet me clip\r\nYour dirty wings\r\nLet me take a ride\r\nDon''t hurt yourself\r\nI want some help\r\nTo help myself\r\nI''ve got some rope\r\nYou have been told\r\nI promise you\r\nI have been true\r\nLet me take a ride\r\nDon''t hurt yourself\r\nI want some help\r\nTo help myself', 2),
(19, 'Territorial Pissings', 'Come on everybody\r\nSmile on your brother\r\nEverybody get together\r\nTry to love one another right now\r\n\r\nWhen I was an alien\r\nCultures weren''t opinions\r\n\r\nGotta find a way\r\nTo find a way\r\nWhen I''m there\r\nGotta find a way\r\nA better way\r\nI had better wait\r\n\r\nNever met a wise man\r\nIf so it''s a woman\r\n\r\nGotta find a way\r\nTo find a way\r\nWhen I''m there\r\nGotta find a way\r\nA better way\r\nI had better wait\r\nGotta find a way\r\nTo find a way\r\nWhen I''m there\r\nGotta find a way\r\nA better way\r\nI had better wait\r\n\r\nJust because you''re paranoid\r\nDon''t mean they''re not after you\r\n\r\nGotta find a way\r\nTo find a way\r\nWhen I''m there\r\nGotta find a way\r\nA better way\r\nGotta find a way\r\nTo find a way\r\nWhen I''m there\r\nGotta find a way\r\nA better way\r\nI had better wait\r\nGotta find a way\r\nTo find a way\r\nWhen I''m there\r\nGotta find a way\r\nA better way\r\nI had better wait\r\nGotta find a way\r\nTo find a way\r\nWhen I''m there\r\nGotta find a way\r\nA better way\r\nI had better wait', 2),
(20, 'Drain You', 'One baby to another says\r\nI''m lucky to have met you\r\nI don''t care what you think unless\r\nIt is about me\r\nIt is now my duty to completely drain you\r\nA travel through a tube and end up in your infection\r\n\r\nChew your meat for you\r\nPass it back and forth\r\nIn a passionate kiss\r\nFrom my mouth to yours\r\n''cause I like you\r\n\r\nWith eyes so dilated\r\nI''ve became your pupil\r\nYou''ve taught me everything\r\nWithout a poison apple\r\nThe water is so yellow\r\nI''m a healthy student\r\nIndebted and so grateful\r\nVacuum out the fluids\r\n\r\nChew your meat for you\r\nPass it back and forth\r\nIn a passionate kiss\r\nFrom my mouth to yours\r\n''cause I like you\r\nYou\r\nYou\r\nYou\r\nYou\r\nYou\r\n\r\nOne baby to another says\r\nI''m lucky to have met you\r\nI don''t care what you think unless\r\nIt is about me\r\nIt is now my duty to completely drain you\r\nA travel through a tube and end up in your infection\r\n\r\nChew your meat for you\r\nPass it back and forth\r\nIn a passionate kiss\r\nFrom my mouth to yours\r\nSloppy it lips to lips\r\nYou''re my vitamins\r\n''cause I''m like you', 2),
(21, 'Lounge Act', 'Truth covered in security\r\nI can''t let you smother me\r\nI''d like to but it wouldn''t work\r\nTrading off and taking turns\r\nI don''t regret a thing\r\n\r\nI''ve got this friend, you see\r\nWho makes me feel\r\nAnd I wanted more\r\nThan I could steal\r\nI''ll arrest myself\r\nAnd wear a shield\r\nI''ll go out of my way\r\nTo prove I still\r\nSmell her on you\r\n\r\nDon''t, tell me what I wanna hear\r\nAfraid of never knowning fear\r\nExperience anything yoy need\r\nI''ll keep fighting jealousy\r\nUntil it''s fucking gone\r\n\r\nI''ve got this friend, you see\r\nWho makes me feel\r\nAnd I wanted more\r\nThan I could steal\r\nI''ll arrest myself\r\nAnd wear a shield\r\nI''ll go out of my way\r\nTo prove I still\r\nSmell her on you\r\n\r\nTruth covered in security\r\nI can''t let you smother me\r\nI''d like to but it wouldn''t work\r\nTrading off and taking turns\r\nI don''t regret a thing\r\n\r\nI''ve got this friend, you see\r\nWho makes me feel\r\nAnd I wanted more\r\nThan I could steal\r\nI''ll arrest myself\r\nAnd wear a shield\r\nI''ll go out of my way\r\nTo make you a deal\r\nWe''ve make a pact\r\nTo learn from who\r\nEver we want\r\nWithout new rules\r\nWe''ll share what''s lost and what we grew\r\nThey''ll go out of their way\r\nTo prove they still\r\nSmell her on you\r\nThey still, smell her on you\r\nSmell her on you', 2),
(22, 'Stay Away', 'Monkey See, monkey do\r\n{I don''t know why}\r\nI''d rather be deal than cool\r\n{I don''t know why}\r\nEvery line ends in rhyme\r\n{I don''t know why}\r\nLess is more, love is blind\r\n{I don''t know why}\r\n\r\nStay\r\nStay away\r\nStay away\r\nStay away\r\n\r\nGive an inch, take a smile\r\n{I don''t know why}\r\nFashion shits, fashion stile\r\n{I don''t know why}\r\nThrow it out and keep it in\r\n{I don''t know why}\r\nHave to have poison skin\r\n{I don''t know why}\r\n\r\nStay\r\nStay away\r\nStay away\r\nStay away\r\n\r\nI don''t know why\r\nI don''t know why\r\n\r\nStay\r\nStay away\r\nStay away\r\nStay away\r\n\r\nMonkey See, monkey do\r\n{I don''t know why}\r\nI''d rather be deal than cool\r\n{I don''t know why}\r\nEvery line ends in rhyme\r\n{I don''t know why}\r\nLess is more, love is blind\r\n{I don''t know why}\r\n\r\nStay\r\nStay away\r\nStay away\r\nStay away\r\n\r\nI don''t know why\r\nI don''t know why\r\n\r\nStay\r\nStay away\r\nStay away\r\nStay away\r\n\r\nStay\r\nStay away\r\nStay away\r\nStay away\r\nStay away\r\nStay away\r\nGod is gay', 2),
(23, 'On A Plain', 'I''ll start this off\r\nWithout any words\r\nI got so high that\r\nI scratched ''til I bled\r\n\r\nLove myself\r\nBetter than you\r\nI know it''s wrong\r\nSo what should I do?\r\n\r\nThe finest day\r\nThat I ever had\r\nWas when I learned\r\nTo cry on command\r\n\r\nLove myself\r\nBetter than you\r\nI know it''s wrong\r\nSo what should I do?\r\n\r\nI''m on a plain\r\nI can''t complain\r\nI''m on a plain\r\n\r\nMy mother died\r\nEvery night\r\nIt''s safe to say\r\nDon''t quote me on that\r\n\r\nLove myself\r\nBetter than you\r\nI know it''s wrong\r\nSo what should I do?\r\n\r\nThe black sheep got\r\nBlackmailed again\r\nForgot to put\r\nOn the zip code\r\n\r\nLove myself\r\nBetter than you\r\nI know it''s wrong\r\nSo what should I do?\r\n\r\nI''m on a plain\r\nI can''t complain\r\nI''m on a plain\r\n\r\nSomewhere I have heard this before\r\nIn a dream my memory has stored\r\nAs defense I''m neutered and spayed\r\nWhat the hell am I trying to say?\r\n\r\nIt is now time\r\nTo make it unclear\r\nTo write off lines\r\nThat don''t make a sense\r\n\r\nLove myself\r\nBetter than you\r\nI know it''s wrong\r\nSo what should I do?\r\n\r\nOne more special\r\nMessage to go\r\nAnd then I''m done\r\nAnd I can go home\r\n\r\nLove myself\r\nBetter than you\r\nI know it''s wrong\r\nSo what should I do?\r\n\r\nI''m on a plain\r\nI can''t complain\r\nI''m on a plain\r\nI can''t complain\r\nI''m on a plain\r\nI can''t complain\r\nI''m on a plain\r\nI can''t complain\r\nI''m on aplain\r\nI can''t complain', 2),
(24, 'Something In The Way', 'Underneath the bridge\r\nThe tarp has sprung a leak\r\nAnd the animals I''ve trapped\r\nHave all become my pets\r\nAnd I''m living off of grass\r\nAnd the drippings from the ceiling\r\nBut it''s ok to eat fish\r\nCause they haven''t any feelings\r\n\r\nSomething in the way\r\nUmmmmm\r\nSomething in the way, yea\r\nUmmmmm\r\nSomething in the way\r\nUmmmmm\r\nSomething in the way, yea\r\nUmmmmm\r\nSomething in the way\r\nUmmmmm\r\nSomething in the way, yea\r\nUmmmmm\r\n\r\nUnderneath the bridge\r\nThe tarp has sprung a leak\r\nAnd the animals I''ve trapped\r\nHave all become my pets\r\nAnd I''m living off of grass\r\nAnd the drippings from the ceiling\r\nBut it''s ok to eat fish\r\nCause they haven''t any feelings\r\n\r\nSomething in the way\r\nUmmmmm', 2),
(25, 'Endless Nameless', 'Silence\r\nHere I am\r\nHere I am\r\nSilent\r\n\r\nBright and clear\r\nIt''s what I am\r\nI have\r\nDied\r\n\r\nuhhhh\r\nuhhhh\r\nuhhhh\r\nuhhhh\r\n\r\nDeath\r\nWith violence\r\nExcitment\r\nRight here\r\n\r\nDied\r\nGo to hell\r\nHere I am\r\nRight here\r\n\r\nOw\r\n\r\nNo mas\r\nNo mas\r\nNo mas\r\nNo mas\r\n\r\nDeath\r\nIs what I am\r\n???\r\n??? ???\r\n\r\nIn back of that\r\nCrime\r\nHere I am\r\nTake a chance\r\nDead\r\n\r\nDie', 2),
(29, 'Serve The Servants', 'Teenage angst has paid off well\r\nNow I''m bored and old\r\nSelf-Appointed judges judge\r\nMore than they have sold\r\n\r\nIf she floats than she is not\r\nA witch like we had thought\r\nA down payment on another\r\nOne at salem''s lot\r\n\r\nServe the servants - Oh no\r\nThat legendary divorce is such a bore\r\n\r\nAs my bones grew they did hurt\r\nThey hurt really bad\r\nI tried hard to have a father\r\nBut instead I had a dad\r\n\r\nI just want you to know that I\r\nDon''t hate you anymore\r\nthere is nothing I could say\r\nthat I haven''t thought before\r\n\r\nServe the servants - oh no\r\nThat legendary divorce is such a bore', 3),
(30, 'Scentless Apprentice', 'Like most babies smell like butter\r\nhis smell smelled like no other\r\nhe was born scentless and senseless\r\nhe was born a scentless apprentice\r\n\r\nGo away - get away, get away, get a-way\r\nevery wet nurse refused to feed him\r\nelectrolytes smell like semen\r\n\r\nI promise not to sell your perfumed secrets\r\nthere are countless formulas for pressing flowers\r\n\r\nI lie in the soll and fertilize mushrooms\r\nLeaking out gas fumes are made into perfume\r\n\r\nYou can''t fire me because I quit\r\nThrow me in the fire and I won''t throw a fit', 3),
(31, 'Heart-Shaped Box', 'She eyes me like a pisces when I am weak\r\nI''ve been locked inside your Heart-Shaped box for a week\r\nI was drawn into your magnet tar pit trap\r\nI wish I could eat your cancer when you turn back\r\n\r\nHey\r\nWait\r\nI''ve got a new conplaint\r\nForever in debt to your priceless advice\r\nHate\r\nHaight\r\nI''ve got a new complaint\r\nForever in debt to your prieless advice\r\nHey\r\nWait\r\nI''ve got a new complaint\r\nForever in debt to your priceless advice\r\n\r\nMeat-eating orchids forgive no one just yet\r\nCut myself angel''s hair and baby''s breath\r\nBroken hymen of your highness I''m left black\r\nThrow down your umbilical noose so I can climb right back', 3),
(32, 'Rape Me', '[Original form:]\r\nRape me, my friend\r\nRape me again \r\n\r\nI''m not the only one\r\nDo it and do it Again\r\n\r\nWaste me \r\nTaste me, my friend \r\n\r\nMy favorite inside source \r\nI''ll kiss your open sores\r\nAppreciate your concern \r\nYou''ll always stink and burn\r\n\r\n[My Form:]\r\nRape me\r\nRape me my friend,\r\nRape me,\r\nRape me again.\r\n\r\nChorus:\r\n\r\nI''m not the only one [x4]\r\n\r\nHelp me,\r\nDo it, and do it again.\r\n\r\nWaste me,\r\nRape me, my friend.\r\n\r\nChorus\r\n\r\nMy favorite inside source,\r\nI''ll kiss your open sores,\r\nAppreciate your concern\r\nYou''ll always, stink, and born.\r\n\r\nChorus\r\n\r\nRape me\r\nRape me\r\n...', 3),
(33, 'Frances Farmer Will Have Her Revenge On Seattle', 'It''s so relieving to know that you''re leaving as soon as you get paid\r\nIt''s so relaxing to hear you''re asking wherever you get your way\r\nI''s so soothing to know that you''ll sue me, this is starting to sound the\r\nsame\r\nI miss the comfort in being sad\r\n\r\nIn her false withness, we hope you''re still with us, to see if they gloar or\r\ndrown\r\nOur favorite paitent, A display of patience, disease-covered Puget Sound\r\nShe''ll come back as fire, to burn all the liars, and leave a blanket of ash\r\non the ground I muss teh comfort in being sad', 3),
(34, 'Dumb', 'I''m not like them\r\nBut I can pretend\r\nThe sun is gone\r\nBut I have a light\r\nThe day is done\r\nBut I''m having fun\r\n\r\nI think I''m dumb\r\nor maybe just happy\r\nThink I''m just happy\r\nmy heart is broke\r\nBut I have some glue\r\nhelp me inhale\r\nAnd mend it with you\r\nWe''ll float around]\r\nAnd hang out on clouds\r\nThen we''ll come down\r\nAnd I have a hangover...Have a hangover\r\n\r\nSkin the sun\r\nFalkl asleep\r\nWish away\r\nThe soul is cheap\r\nLesson learned\r\nWish me luck\r\nSoothe the burn\r\nWake me up\r\n\r\nI''m not like them\r\nBut I can pretend\r\nThe sun is gone\r\nBut I have a light\r\nThe day is done\r\nBut I''m having fun', 3),
(35, 'Very Ape', 'I am buried up to my neck in\r\nContradictionary lies\r\nI take pride as the kind of illiterature\r\nI''m very ape and very nice\r\n\r\nIf you ever need anything please don''t hesitate\r\nto ask someone else first\r\nI''m too busy acting like I''m not naive.\r\nI''ve seen it all I was here first\r\n\r\nOut of the ground\r\nInto the sky\r\nOut of the sky\r\nInto he firt', 3),
(36, 'Milk It', 'I am my own parasite\r\nI don''t need a host to live\r\nWe feed off of each other\r\nWe can share our endorphns\r\nDoll steak, test meat\r\n\r\nI won my own pet virus\r\nI get to pet and name her\r\nHer milk is my shit\r\nMy shit is her milk\r\n\r\nDoll steak, test meat\r\nLook on the bright side is suicide\r\nLost eyesight I''m on your side\r\nAngel left wing, right wing, broken wing\r\nLack of iron and/or sleeping\r\nProtector of the kennel\r\nEcto-plasma\r\nEcto-Skeletal\r\nObituary birthday\r\nYour scent is still here in my place of recovery', 3),
(37, 'Pennyroyal Tea', 'I''m on my time with everyone\r\nI have very bad posture\r\nSit and drink Pennyroyal Tea\r\nDistill the life that''s inside of me\r\nSit and drink Pennyroyal tea\r\nI''m anemic royalty\r\nGive me a Leonard Cohen afterworld\r\nSo I can sigh enternally\r\nI''m so tired I can''t sleep\r\nI''m a liar and a thief\r\n\r\nSit and drink pennyroyal Tea\r\nI''m anemic royalty\r\nI''m on warm milk and laxatives\r\nCherry-flavored antacids', 3),
(38, 'Radio Friendly Unit Shifter', 'Use just once and destroy\r\nInvasion of our piracy\r\nAfterbirth of a nation\r\nStarve without your skeleton key\r\n\r\nI love you for what I am not\r\nI do not want what I have got\r\nA blanket acne''ed with ciggarette burns\r\nSpeak at once while taking turns\r\nSecond-rate third defree burns\r\nWhat is wrong with me\r\nWhat is what I need\r\nWhat do I think I think\r\nThis had nothing to do with what you think\r\nIf you ever think at all\r\nBi-polar opposites attract\r\nAll of a sudden my water broke\r\nhate, hate your enemies\r\nSave, save your friends\r\nFind, find your place\r\nSpeak, speak the truth', 3),
(39, 'Tourette''s', 'Mayday every day, in my heart.\r\nCould''ve had a heart attack, in my heart.\r\nWe don''t know anything, in my heart.\r\nWe all want something fair, in my heart.\r\nHey!\r\nHey!\r\nHeyyyyyyy! [x3]\r\n\r\nOut of town, out of sight, is my heart.\r\nQueen of lies, everyday, in my heart.\r\nMy heart, one more on the phone, my heart.\r\nOne more at the phone, at my heart\r\nHey!\r\nHey!\r\nHeyyyyyyyyyyy! [x2]\r\n\r\nMean heart, cold heart, cold heart, cold heart\r\nCold heart, cold heart, cold heart, cold heart!\r\n\r\nUhhhhhhh!', 3),
(40, 'All Apologies', 'What else should I be\r\nAll apologies\r\nWhat else should I say\r\nEveryone is gay\r\nWhat else could I write\r\nI don''t have the right\r\nWhat else should I be\r\nAll apologies\r\n\r\nIn the sun\r\nIn the sun I feed as one\r\nIn the sun\r\nIn the sun\r\nI''m married\r\nburied\r\nI wish I was like you\r\nEasily amused\r\nFind my nest of salt\r\nEverything is my fault\r\nI''ll take all the blame\r\nAqur scafoam shame\r\nSunburn with freezeburn\r\nChoking on the ashes of her enemy\r\nAll in all we all are', 3),
(41, 'Gallons Of Rubbing Alcohol Flow Through The Strip', 'Mayday every day, in my heart.\r\nCould''ve had a heart attack, in my heart.\r\nWe don''t know anything, in my heart.\r\nWe all want something fair, in my heart.\r\nHey!\r\nHey!\r\nHeyyyyyyy! [x3]\r\n\r\nOut of town, out of sight, is my heart.\r\nQueen of lies, everyday, in my heart.\r\nMy heart, one more on the phone, my heart.\r\nOne more at the phone, at my heart\r\nHey!\r\nHey!\r\nHeyyyyyyyyyyy! [x2]\r\n\r\nMean heart, cold heart, cold heart, cold heart\r\nCold heart, cold heart, cold heart, cold heart!\r\n\r\nUhhhhhhh!', 3);

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `albumler`
--
ALTER TABLE `albumler`
  ADD PRIMARY KEY (`album_id`);

--
-- Tablo için indeksler `sarkilar`
--
ALTER TABLE `sarkilar`
  ADD PRIMARY KEY (`sarki_id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `albumler`
--
ALTER TABLE `albumler`
  MODIFY `album_id` int(12) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=4;
--
-- Tablo için AUTO_INCREMENT değeri `sarkilar`
--
ALTER TABLE `sarkilar`
  MODIFY `sarki_id` int(12) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=42;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
